<a href="https://colab.research.google.com/github/manishakumari13711/2026-ISYS5002-Labs/blob/main/01-labs/Lab10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas requests beautifulsoup4

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (4.13.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.7.22)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (2.10)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time

In [4]:
# Identify the scraper
headers = {
    "User-Agent": "Mozilla/5.0 (Educational purpose scraper)",
    "Accept": "text/html,application/xhtml+xml"
}

# Website URL
url = "https://books.toscrape.com/"

# Download the page
response = requests.get(url, headers=headers, timeout=15)

# Check whether the request was successful
if response.status_code == 200:
    print(
        f"Successfully downloaded the page! "
        f"Content length: {len(response.text)} characters"
    )
else:
    print(f"Failed to download the page. Status code: {response.status_code}")

# Display the first 500 characters
print(response.text[:500])

Successfully downloaded the page! Content length: 51294 characters
<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->
    <head>
        <title>
    All products | Books to Scrape - Sandbox
</title>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8" /

In [5]:
# Convert the downloaded HTML into a BeautifulSoup object
soup = BeautifulSoup(response.text, "html.parser")

# Extract the page title
page_title = soup.title.text.strip()

print(f"Page title: {page_title}")

Page title: All products | Books to Scrape - Sandbox

In [6]:
# Find all book containers
book_containers = soup.find_all("article", class_="product_pod")

print(f"Found {len(book_containers)} books on this page")

# Create empty lists
titles = []
prices = []
ratings = []

# Extract information from each book
for book in book_containers:

    # Get book title
    title = book.h3.a["title"]
    titles.append(title)

    # Get book price
    price = book.find("p", class_="price_color").text.strip()
    prices.append(price)

    # Get star rating
    star_rating = book.find("p", class_="star-rating")["class"][1]
    ratings.append(star_rating)

# Display the first five books
for i in range(min(5, len(titles))):
    print(
        f"Book {i + 1}: {titles[i]}, "
        f"Price: {prices[i]}, Rating: {ratings[i]}"
    )

Found 20 books on this page
Book 1: A Light in the Attic, Price: Â£51.77, Rating: Three
Book 2: Tipping the Velvet, Price: Â£53.74, Rating: One
Book 3: Soumission, Price: Â£50.10, Rating: One
Book 4: Sharp Objects, Price: Â£47.82, Rating: Four
Book 5: Sapiens: A Brief History of Humankind, Price: Â£54.23, Rating: Five

In [7]:
# Combine the three lists into a dictionary
books_data = {
    "Title": titles,
    "Price": prices,
    "Rating": ratings
}

# Create a pandas DataFrame
books_df = pd.DataFrame(books_data)

# Display the table
display(books_df)

                                                Title    Price Rating
0                                A Light in the Attic  Â£51.77  Three
1                                  Tipping the Velvet  Â£53.74    One
2                                          Soumission  Â£50.10    One
3                                       Sharp Objects  Â£47.82   Four
4               Sapiens: A Brief History of Humankind  Â£54.23   Five
5                                     The Requiem Red  Â£22.65    One
6   The Dirty Little Secrets of Getting Your Dream...  Â£33.34   Four
7   The Coming Woman: A Novel Based on the Life of...  Â£17.93  Three
8   The Boys in the Boat: Nine Americans and Their...  Â£22.60   Four
9                                     The Black Maria  Â£52.15    One
10     Starving Hearts (Triangular Trade Trilogy, #1)  Â£13.99    Two
11                              Shakespeare's Sonnets  Â£20.66   Four
12                                        Set Me Free  Â£17.46   Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  Â£52.29   Five
14                          Rip it Up and Start Again  Â£35.02   Five
15  Our Band Could Be Your Life: Scenes from the A...  Â£57.25  Three
16                                               Olio  Â£23.88    One
17  Mesaerion: The Best Science Fiction Stories 18...  Â£37.59    One
18                       Libertarianism for Beginners  Â£51.33    Two
19                            It's Only the Himalayas  Â£45.17    Two

In [9]:
# Re-initialize the DataFrame to ensure a clean run
books_df = pd.DataFrame(books_data)

# Remove all non-numeric characters (except the decimal point) and convert to float
books_df["Price"] = (
    books_df["Price"]
    .str.replace(r"[^0-9.]", "", regex=True)
    .astype(float)
)

# Convert star ratings into numbers
rating_mapping = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

books_df["Rating"] = books_df["Rating"].map(rating_mapping)

# Display the cleaned data
display(books_df)

                                                Title  Price  Rating
0                                A Light in the Attic  51.77       3
1                                  Tipping the Velvet  53.74       1
2                                          Soumission  50.10       1
3                                       Sharp Objects  47.82       4
4               Sapiens: A Brief History of Humankind  54.23       5
5                                     The Requiem Red  22.65       1
6   The Dirty Little Secrets of Getting Your Dream...  33.34       4
7   The Coming Woman: A Novel Based on the Life of...  17.93       3
8   The Boys in the Boat: Nine Americans and Their...  22.60       4
9                                     The Black Maria  52.15       1
10     Starving Hearts (Triangular Trade Trilogy, #1)  13.99       2
11                              Shakespeare's Sonnets  20.66       4
12                                        Set Me Free  17.46       5
13  Scott Pilgrim's Precious Little Life (Scott Pi...  52.29       5
14                          Rip it Up and Start Again  35.02       5
15  Our Band Could Be Your Life: Scenes from the A...  57.25       3
16                                               Olio  23.88       1
17  Mesaerion: The Best Science Fiction Stories 18...  37.59       1
18                       Libertarianism for Beginners  51.33       2
19                            It's Only the Himalayas  45.17       2

In [10]:
# Display basic statistics
print("Basic statistics:")
display(books_df.describe())

# Calculate average price for each rating
avg_price_by_rating = (
    books_df.groupby("Rating")["Price"]
    .mean()
    .sort_index()
)

print("Average price by rating:")
display(avg_price_by_rating)

Basic statistics:

           Price     Rating
count  20.000000  20.000000
mean   38.048500   2.850000
std    15.135231   1.565248
min    13.990000   1.000000
25%    22.637500   1.000000
50%    41.380000   3.000000
75%    51.865000   4.000000
max    57.250000   5.000000

Average price by rating:

Rating
1    40.018333
2    36.830000
3    42.316667
4    31.105000
5    39.750000
Name: Price, dtype: float64

In [11]:
# Create empty lists to store all books
all_titles = []
all_prices = []
all_ratings = []

# Scrape the first three pages
for page_num in range(1, 4):

    # Construct the correct URL
    if page_num == 1:
        page_url = "https://books.toscrape.com/"
    else:
        page_url = (
            f"https://books.toscrape.com/catalogue/"
            f"page-{page_num}.html"
        )

    # Wait one second between requests
    time.sleep(1)

    try:
        # Download the page
        response = requests.get(
            page_url,
            headers=headers,
            timeout=15
        )

        # Check whether the request was successful
        response.raise_for_status()

        print(f"Successfully scraped page {page_num}")

        # Parse HTML
        soup = BeautifulSoup(response.text, "html.parser")

        # Find all book containers
        book_containers = soup.find_all(
            "article",
            class_="product_pod"
        )

        # Extract information from each book
        for book in book_containers:

            # Extract title
            title = book.h3.a["title"]
            all_titles.append(title)

            # Extract price
            price = book.find(
                "p",
                class_="price_color"
            ).text.strip()
            all_prices.append(price)

            # Extract rating
            rating = book.find(
                "p",
                class_="star-rating"
            )["class"][1]
            all_ratings.append(rating)

        print(f"Books found on page {page_num}: "
              f"{len(book_containers)}")

    except requests.RequestException as error:
        print(f"Failed to scrape page {page_num}: {error}")

# Create a DataFrame containing all successfully scraped books
all_books_df = pd.DataFrame({
    "Title": all_titles,
    "Price": all_prices,
    "Rating": all_ratings
})

print("\nTotal books collected:", len(all_books_df))

# Display the collected books
display(all_books_df)

Successfully scraped page 1
Books found on page 1: 20
Successfully scraped page 2
Books found on page 2: 20
Successfully scraped page 3
Books found on page 3: 20

Total books collected: 60

                                                Title    Price Rating
0                                A Light in the Attic  Â£51.77  Three
1                                  Tipping the Velvet  Â£53.74    One
2                                          Soumission  Â£50.10    One
3                                       Sharp Objects  Â£47.82   Four
4               Sapiens: A Brief History of Humankind  Â£54.23   Five
5                                     The Requiem Red  Â£22.65    One
6   The Dirty Little Secrets of Getting Your Dream...  Â£33.34   Four
7   The Coming Woman: A Novel Based on the Life of...  Â£17.93  Three
8   The Boys in the Boat: Nine Americans and Their...  Â£22.60   Four
9                                     The Black Maria  Â£52.15    One
10     Starving Hearts (Triangular Trade Trilogy, #1)  Â£13.99    Two
11                              Shakespeare's Sonnets  Â£20.66   Four
12                                        Set Me Free  Â£17.46   Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  Â£52.29   Five
14                          Rip it Up and Start Again  Â£35.02   Five
15  Our Band Could Be Your Life: Scenes from the A...  Â£57.25  Three
16                                               Olio  Â£23.88    One
17  Mesaerion: The Best Science Fiction Stories 18...  Â£37.59    One
18                       Libertarianism for Beginners  Â£51.33    Two
19                            It's Only the Himalayas  Â£45.17    Two
20                                        In Her Wake  Â£12.84    One
21                                    How Music Works  Â£37.32    Two
22  Foolproof Preserving: A Guide to Small Batch J...  Â£30.52  Three
23                         Chase Me (Paris Nights #2)  Â£25.27   Five
24                                         Black Dust  Â£34.53   Five
25                      Birdsong: A Story in Pictures  Â£54.64  Three
26  America's Cradle of Quarterbacks: Western Penn...  Â£22.50  Three
27                     Aladdin and His Wonderful Lamp  Â£53.13  Three
28  Worlds Elsewhere: Journeys Around Shakespeareâ...  Â£40.30   Five
29                                     Wall and Piece  Â£44.18   Four
30  The Four Agreements: A Practical Guide to Pers...  Â£17.66   Five
31  The Five Love Languages: How to Express Heartf...  Â£31.05  Three
32                                  The Elephant Tree  Â£23.82   Five
33                             The Bear and the Piano  Â£36.89    One
34                                     Sophie's World  Â£15.94   Five
35                                        Penny Maybe  Â£33.29  Three
36     Maude (1883-1993):She Grew Up with the country  Â£18.02    Two
37                               In a Dark, Dark Wood  Â£19.63    One
38                                Behind Closed Doors  Â£52.22   Four
39                     You can't bury them all: Poems  Â£33.63    Two
40                     Slow States of Collapse: Poems  Â£57.31  Three
41                              Reasons to Stay Alive  Â£26.41    Two
42                        Private Paris (Private #10)  Â£47.61   Five
43  #HigherSelfie: Wake Up Your Life. Free Your So...  Â£23.11   Five
44                    Without Borders (Wanderlove #1)  Â£45.07    Two
45                                   When We Collided  Â£31.77    One
46                       We Love You, Charlie Freeman  Â£50.27   Five
47            Untitled Collection: Sabbath Poems 2014  Â£14.27   Four
48  Unseen City: The Majesty of Pigeons, the Discr...  Â£44.18   Four
49                                     Unicorn Tracks  Â£18.78  Three
50  Unbound: How Eight Technologies Made Us Human,...  Â£25.52    One
51  Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRo...  Â£16.28    One
52  Throwing Rocks at the Google Bus: How Growth B...  Â£31.12  Three
53                                    This One Summer  Â£19.49   Four
54                                             Thirst  Â£17.27   Five
55        The Torch Is Passed: A Harding Family Story  Â£19.09    One
56                    The Secret of Dreadwillow Carse  Â£56.13    One
57  The Pioneer Woman Cooks: Dinnertime: Comfort C...  Â£56.41    One
58                                The Past Never Ends  Â£56.50   Four
59  The Natural History of Us (The Fine Art of Pre...  Â£45.22  Three

In [13]:
# Re-initialize the DataFrame to ensure a clean run
all_books_df = pd.DataFrame({
    "Title": all_titles,
    "Price": all_prices,
    "Rating": all_ratings
})

# Remove all non-numeric characters (except the decimal point) and convert to float
all_books_df["Price"] = (
    all_books_df["Price"]
    .str.replace(r"[^0-9.]", "", regex=True)
    .astype(float)
)

# Convert rating words into numbers
rating_mapping = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

all_books_df["Rating"] = all_books_df["Rating"].map(
    rating_mapping
)

# Display basic statistics
print("Basic statistics for all scraped books:")
display(all_books_df.describe())

# Calculate average price by rating
avg_price_by_rating = (
    all_books_df.groupby("Rating")["Price"]
    .mean()
    .sort_index()
)

print("Average price by rating:")
display(avg_price_by_rating)

Basic statistics for all scraped books:

           Price     Rating
count  60.000000  60.000000
mean   35.002667   3.000000
std    14.553082   1.507046
min    12.840000   1.000000
25%    22.040000   1.750000
50%    33.485000   3.000000
75%    50.142500   4.000000
max    57.310000   5.000000

Average price by rating:

Rating
1    34.311333
2    33.867500
3    38.808462
4    35.526000
5    32.484286
Name: Price, dtype: float64